const errorCodes = {
    // General errors
    ER_FORBIDDEN: 'ER_FORBIDDEN',
    ER_UNAUTHORIZED: 'ER_UNAUTHORIZED',
    ER_INTERNAL: 'ER_INTERNAL',
    ER_INVALID_FORMAT: 'ER_INVALID_FORMAT',
    ER_USER_NOT_FOUND: 'ER_USER_NOT_FOUND',
    ER_SENSOR_NOT_FOUND: 'ER_SENSOR_NOT_FOUND',
    ER_TOKEN_EXPIRED: 'ER_TOKEN_EXPIRED',

    // Subscriptions and Sharing
    ER_SUBSCRIPTION_NOT_FOUND: 'ER_SUBSCRIPTION_NOT_FOUND',
    ER_SHARE_COUNT_REACHED: 'ER_SHARE_COUNT_REACHED',
    ER_SENSOR_SHARE_COUNT_REACHED: 'ER_SENSOR_SHARE_COUNT_REACHED',
    ER_NO_DATA_TO_SHARE: 'ER_NO_DATA_TO_SHARE',
    ER_SENSOR_ALREADY_SHARED: 'ER_SENSOR_ALREADY_SHARED',
    ER_SENSOR_ALREADY_SHARED: 'ER_SENSOR_ALREADY_CLAIMED',
    ER_UNABLE_TO_SEND_EMAIL: 'ER_UNABLE_TO_SEND_EMAIL',

    // Argument errors
    ER_MISSING_ARGUMENT: 'ER_MISSING_ARGUMENT',
    ER_INVALID_DENSITY_MODE: 'ER_INVALID_DENSITY_MODE',
    ER_INVALID_SORT_MODE: 'ER_INVALID_SORT_MODE',
    ER_INVALID_TIME_RANGE: 'ER_INVALID_TIME_RANGE',
    ER_INVALID_EMAIL_ADDRESS: 'ER_INVALID_EMAIL_ADDRESS',
    ER_INVALID_MAC_ADDRESS: 'ER_INVALID_MAC_ADDRESS',

    // Sub-codes
    ER_SUB_DATA_STORAGE_ERROR: 'ER_SUB_DATA_STORAGE_ERROR',
    ER_SUB_NO_USER: 'ER_SUB_NO_USER'
};

/**
 * Exports
 */
module.exports = errorCodes;