name: Deploy to Staging
on: 
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying staging on ${{ runner.os }} from branch ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup NPM
        uses: actions/setup-node@v2
        with:
          node-version: '12'
        run: npm install
        run: ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
