on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: SonarCloud
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get master
      run: git fetch origin master
    - name: Install dependencies
      run:  npm install
    - name: Install global dependencies
      run:  ./install_dependencies.sh --include-serverless
    - name: Setup Credentials
      run: |
        echo \
        "module.exports = { \
          prod: { \
          primary: 'PRODUCTION ACCESS TOKEN 1', \
          primaryEmail: 'test@ruuvi.com', \
          secondary: 'PRODUCTION ACCESS TOKEN 2',\
          secondaryEmail: 'test2@ruuvi.com', \
          unregisteredEmail: 'test3@ruuvi.com', \
          url: 'PRODUCTION URL', \
          internalKey: 'hello-there' \
          }, \
          dev: { \
          primary: 'DEV ACCESS TOKEN 1', \
          primaryEmail: 'test@ruuvi.com', \
          secondary: 'DEV ACCESS TOKEN 2', \
          secondaryEmail: 'test2@ruuvi.com', \
          unregisteredEmail: 'test3@ruuvi.com', \
          url: 'DEVELOPMENT URL', \
          internalKey: 'hello-there' \
          } \
        };" > tests/integration/integrationCredentials.js
    - name: serverless configure profile
      run: |
        serverless config credentials \
        --provider aws \
        --key ${{ secrets.AWS_ACCESS_KEY_ID }} \
        --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} \
        --profile ruuvi
    - name: serverless deploy
      run: serverless deploy
    - name: Run Tests
      run:  jest --coverage
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
